### PR TITLE
Added first and last names to the connections section on the home page. 

### PR DESCRIPTION
**Pull request by RandomUserWithInternet**
The issue in particular: https://github.com/akhilchoudhary2k/MindMatch-kgp/issues/34

I had trouble test running my code because I didn't set up the local database properly. If someone could test run and confirm it works, that would be great. For now, I'm labeling this as a draft. 

I edited app.js to include a function to look up the names, and edited UserHome.ejs to add it to the page.

### CODE REVIEW

**Comment by akhilchoudhary2k** [comment]
@RandomUserWithInternet I tried running your code locally
3 suggestions:
1. we cant call a function from an ejs file, so do all the function calling and backend stuff & then render the ejs pages with parameters.
2. instead of getting full names for all users, we can simple run a loop and pass username to `getFullName()` and get [fname, lname]. and append it to a list then pass this list to ejs page. And we'll have fnames & lnames in the required order 
3. instead of promise use **async** & **await**, it's simple 
e.g.

`app.get ( "..." ,`**`async`**`function(req, res) {`
`      .....`
      **`await`**`timeTakingFunctionCall();`
`      .....`
`});`

**Comment by RandomUserWithInternet** [comment]
From what I saw, the res.render() only allows me to send objects. I think I'll just make all the IDs ```i``` .

**Comment by akhilchoudhary2k** [comment]
@RandomUserWithInternet Install a working setup of mongodb in your machine otherwise, you won't be able to run & test your code. so no point working ahead without any means to check it.

**Comment by akhilchoudhary2k** [comment]
@RandomUserWithInternet pls resolve the conflicts, I'll run and test your PR

**Comment by RandomUserWithInternet** [comment]
I have some personal stuff going on so if you could assign it to someone
else, that would be best. If not, I can get back to you around Tuesday next
week.

**Comment by akhilchoudhary2k** [comment]
No worries, I don't have any urgency to close this. If you wanna continue working next week take your time.

**Comment by RandomUserWithInternet** [comment]
I have no clue what I just did. I changed a bunch of the code and was going to edit the pull request but I must've done something wrong...

**Pull request closed without merging**
